package views;

import controllers.ManageSalesController;
import controllers.PrincipalController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rosan
 */
public class UserMenuView extends javax.swing.JFrame {

    private PrincipalController controller;
    private int selection;

    /**
     * Creates new form UserMenuView
     */
    public UserMenuView(PrincipalController controller) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_showActiveSales = new javax.swing.JButton();
        jb_showNextSales = new javax.swing.JButton();
        jb_leaveActiveSale = new javax.swing.JButton();
        jb_showMsnEndSales = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jb_manageOwnSales = new javax.swing.JButton();
        lb_menuTittle = new javax.swing.JLabel();
        jB_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jb_showActiveSales.setText("Ver subastas activas");
        jb_showActiveSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_showActiveSalesActionPerformed(evt);
            }
        });

        jb_showNextSales.setText("Ver subastas próximas");
        jb_showNextSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_showNextSalesActionPerformed(evt);
            }
        });

        jb_leaveActiveSale.setText("Abandonar subasta activa");
        jb_leaveActiveSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_leaveActiveSaleActionPerformed(evt);
            }
        });

        jb_showMsnEndSales.setText("Ver mensajes de subastas finalizadas");
        jb_showMsnEndSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_showMsnEndSalesActionPerformed(evt);
            }
        });

        jButton5.setText("Ver mensajes de subastas registradas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jb_manageOwnSales.setText("Administrar subastas propias");
        jb_manageOwnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_manageOwnSalesActionPerformed(evt);
            }
        });

        lb_menuTittle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_menuTittle.setText("Menú principal");

        jB_exit.setText("Salir");
        jB_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_exitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/subasta.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB_exit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_menuTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_manageOwnSales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_showActiveSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_showNextSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_leaveActiveSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_showMsnEndSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_menuTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(jb_showActiveSales)
                .addGap(18, 18, 18)
                .addComponent(jb_showNextSales)
                .addGap(18, 18, 18)
                .addComponent(jb_leaveActiveSale)
                .addGap(18, 18, 18)
                .addComponent(jb_showMsnEndSales)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jb_manageOwnSales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jB_exit)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_exitActionPerformed
        JOptionPane.showMessageDialog(null, "Muchas Garcias por usar nuestro servicio de subastas\nVuelva Pronto");
        System.exit(0);
    }//GEN-LAST:event_jB_exitActionPerformed

    private void jb_showActiveSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_showActiveSalesActionPerformed

    }//GEN-LAST:event_jb_showActiveSalesActionPerformed

    private void jb_showNextSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_showNextSalesActionPerformed

    }//GEN-LAST:event_jb_showNextSalesActionPerformed

    private void jb_leaveActiveSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_leaveActiveSaleActionPerformed

    }//GEN-LAST:event_jb_leaveActiveSaleActionPerformed

    private void jb_showMsnEndSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_showMsnEndSalesActionPerformed

    }//GEN-LAST:event_jb_showMsnEndSalesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jb_manageOwnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_manageOwnSalesActionPerformed
        
        try {
            this.selection = 6;
            controller.selectAction(selection);
            controller.showManageSale(controller, this);
        } catch (IOException ex) {
             JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_jb_manageOwnSalesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_exit;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb_leaveActiveSale;
    private javax.swing.JButton jb_manageOwnSales;
    private javax.swing.JButton jb_showActiveSales;
    private javax.swing.JButton jb_showMsnEndSales;
    private javax.swing.JButton jb_showNextSales;
    private javax.swing.JLabel lb_menuTittle;
    // End of variables declaration//GEN-END:variables
}
