package observerApproveSale;

import models.SaleModel;

/**
 *
 * @author rosan
 */
public class ShowSaleAprove extends javax.swing.JFrame {

    private SaleModel sale;

    public ShowSaleAprove(SaleModel sale) {
        initComponents();
        this.sale = sale;
        initShowSaleInformation();
        //ThreadApproveSale threadApproveSale = new ThreadApproveSale();
        //threadApproveSale.start();
    }

    private void initShowSaleInformation() {
        ta_saleInformation.setEditable(false);
        ta_saleInformation.setText(sale.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta_saleInformation = new javax.swing.JTextArea();
        jb_dateStartSale = new javax.swing.JLabel();
        tf_dateStartSale = new javax.swing.JTextField();
        jb_approve = new javax.swing.JButton();
        jb_disapprove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta_saleInformation.setColumns(20);
        ta_saleInformation.setRows(5);
        jScrollPane1.setViewportView(ta_saleInformation);

        jb_dateStartSale.setText("Fecha de inicio de la subasta");

        jb_approve.setText("Aprobar");

        jb_disapprove.setText("Desaprobar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jb_dateStartSale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_dateStartSale))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jb_approve, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jb_disapprove)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_dateStartSale)
                    .addComponent(tf_dateStartSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_approve)
                    .addComponent(jb_disapprove))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_approve;
    private javax.swing.JLabel jb_dateStartSale;
    private javax.swing.JButton jb_disapprove;
    private javax.swing.JTextArea ta_saleInformation;
    private javax.swing.JTextField tf_dateStartSale;
    // End of variables declaration//GEN-END:variables
}
