package views;

import controllers.PrincipalControllerServer;
import java.util.List;
import javax.swing.DefaultListModel;
import models.SaleModel;

/**
 *
 * @author
 */
public class ShowSaleApproveList extends javax.swing.JFrame {

    private PrincipalControllerServer controller;

    public ShowSaleApproveList(PrincipalControllerServer controller) {
        this.controller = controller;
        initComponents();
        initSaleWaitingList();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SaleApproveList = new javax.swing.JList<String>();
        lbContactLisr = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        bt_approve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        SaleApproveList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(SaleApproveList);

        lbContactLisr.setText("Contact List");

        bt_back.setText("Regresar");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        bt_approve.setText("Aprobar");
        bt_approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_approveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbContactLisr)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_approve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                        .addComponent(bt_back)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lbContactLisr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_back)
                    .addComponent(bt_approve))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        controller.showAdministartorMenuView(controller, this);
    }//GEN-LAST:event_bt_backActionPerformed

    private void bt_approveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_approveActionPerformed


    }//GEN-LAST:event_bt_approveActionPerformed

//    public int movieSelected() {
//        return listMovies.getSelectedIndex();
//    }
    private void initSaleWaitingList() {

        DefaultListModel model = new DefaultListModel();
        List<SaleModel> sale = controller.showWaitingListSale();
        for (int i = 0; i < sale.size(); i++) {
            model.addElement(sale.get(i));
            System.out.println("" + sale.get(i).toString());
        }
        SaleApproveList.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> SaleApproveList;
    private javax.swing.JButton bt_approve;
    private javax.swing.JButton bt_back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbContactLisr;
    // End of variables declaration//GEN-END:variables
}
