package views;

import controllers.PrincipalControllerServer;

/**
 *
 * @author Edgardo Quirós
 */
public class AdministratorMenuView extends javax.swing.JFrame {

    private PrincipalControllerServer controller;
    private int selection;

    /**
     * Creates new form AdministratorMenuView
     */
    public AdministratorMenuView(PrincipalControllerServer controller) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_ApproveSale = new javax.swing.JButton();
        jbNextSales = new javax.swing.JButton();
        jbActiveSales = new javax.swing.JButton();
        jbEndedSales = new javax.swing.JButton();
        jbUserLists = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jB_returnView = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jb_ApproveSale.setText("Aprobar Subastas");
        jb_ApproveSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ApproveSaleActionPerformed(evt);
            }
        });

        jbNextSales.setText("Subastas Proximas ");
        jbNextSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextSalesActionPerformed(evt);
            }
        });

        jbActiveSales.setText("Subastas Activas");
        jbActiveSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActiveSalesActionPerformed(evt);
            }
        });

        jbEndedSales.setText("Subastas Finalizadas");
        jbEndedSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEndedSalesActionPerformed(evt);
            }
        });

        jbUserLists.setText("Lista de Usuarios");
        jbUserLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUserListsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Menu de Administrador");

        jB_returnView.setText("Regresar");
        jB_returnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_returnViewActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/subastaCoches.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbEndedSales, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbUserLists, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbActiveSales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbNextSales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jB_returnView, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_ApproveSale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jb_ApproveSale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNextSales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbActiveSales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEndedSales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbUserLists)
                        .addGap(32, 32, 32)
                        .addComponent(jB_returnView)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_ApproveSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ApproveSaleActionPerformed
        this.selection = 1;
    }//GEN-LAST:event_jb_ApproveSaleActionPerformed

    private void jB_returnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_returnViewActionPerformed
        controller.NoConnection(controller);
        this.dispose();
    }//GEN-LAST:event_jB_returnViewActionPerformed

    private void jbNextSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextSalesActionPerformed
        this.selection = 2;
    }//GEN-LAST:event_jbNextSalesActionPerformed

    private void jbActiveSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActiveSalesActionPerformed
        this.selection = 3;
    }//GEN-LAST:event_jbActiveSalesActionPerformed

    private void jbEndedSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEndedSalesActionPerformed
        this.selection = 4;
    }//GEN-LAST:event_jbEndedSalesActionPerformed

    private void jbUserListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUserListsActionPerformed
        this.selection = 5;
    }//GEN-LAST:event_jbUserListsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdministratorMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdministratorMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdministratorMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdministratorMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdministratorMenuView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_returnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbActiveSales;
    private javax.swing.JButton jbEndedSales;
    private javax.swing.JButton jbNextSales;
    private javax.swing.JButton jbUserLists;
    private javax.swing.JButton jb_ApproveSale;
    // End of variables declaration//GEN-END:variables
}
