package views;

import FormatDates.DateFormatString;
import controllers.PrincipalController;
import java.io.IOException;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Ana Teresa
 */
public class RegisterUserView extends javax.swing.JFrame {

    private String schedule;
    private String name;
    private String email;
    private String password;
    private Calendar calendar;
    private String numberPhone;

    private PrincipalController controller;

    /**
     * Creates new form RegisterUserView
     *
     * @param controller
     */
    public RegisterUserView(PrincipalController controller) {
        this.controller = controller;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private boolean initVariables() throws IOException {
        try {
            this.schedule = jT_Schedule.getText();
            this.name = jT_Name.getText();
            this.email = jT_Email.getText();
            this.password = jT_Password.getText();
            this.calendar = DateFormatString.getCalendarFormat(jT_Birthdate.getText());
            this.numberPhone = jT_Tel.getText();
            return true;
        } catch (ParseException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Hay datos que se encuentran vacíos o con formato incorrecto\n");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelName = new javax.swing.JLabel();
        jLabelSchedule = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelContrasenna = new javax.swing.JLabel();
        jLabelBirthdate = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jT_Schedule = new javax.swing.JTextField();
        jT_Name = new javax.swing.JTextField();
        jT_Email = new javax.swing.JTextField();
        jT_Password = new javax.swing.JTextField();
        jT_Birthdate = new javax.swing.JTextField();
        jT_Tel = new javax.swing.JTextField();
        jB_return = new javax.swing.JButton();
        jB_register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelName.setText("Nombre");

        jLabelSchedule.setText("Cédula");

        jLabelEmail.setText("Correo");

        jLabelContrasenna.setText("Contraseña");

        jLabelBirthdate.setText("Fecha Nacimiento");

        jLabelTel.setText("Teléfono");

        jT_Schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jT_ScheduleMouseReleased(evt);
            }
        });

        jT_Birthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_BirthdateActionPerformed(evt);
            }
        });

        jB_return.setText("Regresar");
        jB_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_returnActionPerformed(evt);
            }
        });

        jB_register.setText("Registrar");
        jB_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_registerActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/correctRegister.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelContrasenna)
                    .addComponent(jLabelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthdate)
                    .addComponent(jLabelName)
                    .addComponent(jLabelSchedule))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_Name)
                            .addComponent(jT_Email)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jT_Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 116, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jT_Tel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_Birthdate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_Password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_register)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_return)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jT_Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jT_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Birthdate, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jT_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_register)
                    .addComponent(jB_return))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_BirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_BirthdateActionPerformed

    }//GEN-LAST:event_jT_BirthdateActionPerformed

    private void jB_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_registerActionPerformed

        try {
            boolean continueWriting = this.initVariables();
            if (continueWriting) {
                controller.processConfirmationAction(continueWriting);
                boolean status = controller.createUser(schedule, name, email, password, calendar, numberPhone);
                JOptionPane.showMessageDialog(null, "Resultado de Registrar\n" + controller.messageRegister(status));
                if (status) {
                    controller.showMenu(controller);
                } else {
                    controller.returnView(controller, this);
                }
            } else {
                controller.processConfirmationAction(continueWriting);
                controller.returnView(controller, this);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_jB_registerActionPerformed

    private void jB_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_returnActionPerformed

        try {
            controller.processConfirmationAction(false);
            controller.returnView(controller, this);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jB_returnActionPerformed

    private void jT_ScheduleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_ScheduleMouseReleased
        jT_Schedule.setToolTipText("La cédula debe contener 9 números");
    }//GEN-LAST:event_jT_ScheduleMouseReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegisterUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegisterUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegisterUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegisterUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegisterUserView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_register;
    private javax.swing.JButton jB_return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBirthdate;
    private javax.swing.JLabel jLabelContrasenna;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSchedule;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jT_Birthdate;
    private javax.swing.JTextField jT_Email;
    private javax.swing.JTextField jT_Name;
    private javax.swing.JTextField jT_Password;
    private javax.swing.JTextField jT_Schedule;
    private javax.swing.JTextField jT_Tel;
    // End of variables declaration//GEN-END:variables
}
